### ISSUE TITLE
Allow to remove all listeners by topic.

### ISSUE THREAD

**Issue by SkeLLLa** [mcollina/mqemitter#12]
Hi. Could `removeListener` method be modified in order to provide option to remove all listeners by topic?

E.g. this line could be removed https://github.com/mcollina/mqemitter/blob/master/mqemitter.js#L87 in order to achieve the result. Or it can be done like in node's even emitter by separate method.

It might be useful when some changes were made to even source and you no longer have some topics. Now if you don't have all handler function reference you can't clear Qlobber matcher.

Also I think it worth to add kind of `clear` method that will call Qlobber's `clear` method to allow clearing all listeners.

**Comment by mcollina** [comment]
Doing this would be a semver-major change that needs to be percolated by all the implementers of this interface. I'd try to avoid this as much as possible.

What's the use case for this?

**Comment by SkeLLLa** [comment]
@mcollina to avoid semver-major change we can add new method just like it's done in node's event emitter: `removeListener` and `removeAllListeners`.

Now to remove a listener you should have a reference to handler function. If mqemitter is used in some kind of pubsub `publisher -> mqemitter -> subscribers`. Usually stuff related to publisher and subscribers are implemented in different modules.

And if you receive some special command that will command publisher to stop sending messages on specific topic, now you'll need some shared mapping object that will store `topic -> handers[]` mapping and you need to iterate over it and call removeListener for each handler instead of just removing all listeners just by calling qlobber method.

**Comment by mcollina** [comment]
Adding `removeAllListener` will still require an addition to all implementors of this interface.

**Comment by SkeLLLa** [comment]
Ah, I understand. Then I'll make a module similar to this one. I think it will be something like mqemitter + evenemitter3 (with it's contexts) + promises instead of callbacks,/

If you don't mind I'll call it like mqemitter3 or something like that :).

**Comment by mcollina** [comment]
Go ahead!

**Comment by SkeLLLa** [comment]
Here's some initial implementation https://github.com/SkeLLLa/mqee. As for performance it ~ 2 times slower then this one. Probably because of promises stuff. So if you have some suggestions - you're welcome.

**Comment by mcollina** [comment]
I don't have many recommendations minus trying to avoid some of the promise allocations in https://github.com/SkeLLLa/mqee/blob/05461ef3d1ada2e55fdb75e2e8e0964c3539b426/src/index.ts#L77. I would still use callbacks internally and just use promises on the API.
