### ISSUE TITLE
should MQEmitter instance reference be passed to `_parallel` ?

### ISSUE THREAD

**Issue by getlarge** [mcollina/mqemitter#218]
Hi,

I am working on an instrumentation library for Aedes and during this work i needed to access the `Client`  instance passed to `handleSubscribe` inside the function passed to `Aedes.subscribe` and invoked in `MQEmitter._do`. 
With @robertsLando we noticed that an invalid (or at least questionable) `this` reference was passed when calling _parallel , we have been wondering why the reference to `MQEmitter` instance was passed since it would override the binding from the function originally passed to `MQEmitter.on`.

Here's a suggested change if you agree.
---

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `mqemitter@5.0.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/mqemitter/mqemitter.js b/node_modules/mqemitter/mqemitter.js
index 7d556e8..898125d 100644
--- a/node_modules/mqemitter/mqemitter.js
+++ b/node_modules/mqemitter/mqemitter.js
@@ -130,7 +130,7 @@ MQEmitter.prototype._do = function (message, callback) {
   const matches = this._matcher.match(message.topic)
 
   this.current++
-  this._parallel(this, matches, message, callback)
+  this._parallel(undefined, matches, message, callback)
 
   return this
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by robertsLando** [comment]
cc @mcollina

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by getlarge** [comment]
Thanks for asking, it seems like it is not really a problem on MQEmitter side.
When trying to produce the expected issue, i just learned that the `this` set via `bind` method is not overriden by `call` method. So to have the correct `this` inside the function called by `MQEmitter._do` is the responsibility of the MQEmitter API consumer.
The only benefit (if we can call it like this), in setting `undefined` instead of `this` in [MQEmitter._do](https://github.com/mcollina/mqemitter/blob/master/mqemitter.js#L133) is that it would result in a `TypeError Cannot read properties of undefined ...` if the user forget to bind the correct `this`. Currently it would just silently fail ...

```js
function Parent(){
  this.name = 'parent'
}

Parent.prototype.say = function(cb){
  console.log(this.name)
  cb()
}

const parent = new Parent()

// prints parent\ndone
parent.say(() => {console.log('done')})
// prints parent\ndone
parent.say.bind(parent).call(mq, () => {console.log('done')})
// prints undefined\ndone
parent.say.call(mq, () => {console.log('done')})
```

**Comment by mcollina** [comment]
Setting `this` in that way is actually a feature, closing then.
