### ISSUE TITLE
Questions regarding this package (back pressure regulation)

### ISSUE THREAD

**Issue by kamikazechaser** [mcollina/mqemitter#44]
I was going through #4 and I had some questions.

Would you recommend this as a drop-in replacement for `EventEmitter`/[EventEmitter3](https://github.com/primus/eventemitter3). One of the libraries I maintain (https://github.com/yagop/node-telegram-bot-api) uses EventEmitter3 as the pipeline engine. A user reported [here](https://github.com/yagop/node-telegram-bot-api/issues/705#issuecomment-520631389) that back pressure regulation is impossible with EventEmitter3 thus affecting scalability.

Could this library be a better drop in replacement?

**Comment by mcollina** [comment]
It's not "drop in" as it will likely require some API changes. However this is implements backpressure.
